version: '3.7'

services:
  node:
    build:
      context: .
      dockerfile: docker/node.dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: '${NAME}-node'
    command: yarn run dev
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
